services:
  db:
    container_name: sweet-sprouts-db
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - sweet-sprouts-db-volume:/var/lib/postgresql/data

volumes:
  sweet-sprouts-db-volume:
